using Dapper;
using Microsoft.Data.Sqlite;
using Microsoft.Extensions.Logging;
using SharedKernel.Data;
using SharedKernel.Domain;

namespace TradingSupervisorService.Repositories;

/// <summary>
/// Data model for alert_history table records.
/// Immutable record for type safety and value equality.
/// </summary>
public sealed record AlertRecord
{
    public string AlertId { get; init; } = string.Empty;
    public string AlertType { get; init; } = string.Empty;
    public string Severity { get; init; } = string.Empty;
    public string Message { get; init; } = string.Empty;
    public string? DetailsJson { get; init; }
    public string SourceService { get; init; } = string.Empty;
    public string CreatedAt { get; init; } = string.Empty;  // ISO8601
    public string? ResolvedAt { get; init; }  // ISO8601
    public string? ResolvedBy { get; init; }
}

/// <summary>
/// Repository interface for alert_history table.
/// Stores all alerts raised by the trading system for audit and notification.
/// </summary>
public interface IAlertRepository
{
    /// <summary>
    /// Inserts a new alert record.
    /// Alert IDs should be unique GUIDs generated by the caller.
    /// </summary>
    Task InsertAsync(AlertRecord alert, CancellationToken ct);

    /// <summary>
    /// Gets all unresolved alerts (resolved_at IS NULL).
    /// Results are ordered by created_at DESC (most recent first).
    /// </summary>
    Task<IReadOnlyList<AlertRecord>> GetUnresolvedAsync(int limit, CancellationToken ct);

    /// <summary>
    /// Gets alerts filtered by severity and time range.
    /// Results are ordered by created_at DESC.
    /// </summary>
    Task<IReadOnlyList<AlertRecord>> GetBySeverityAsync(AlertSeverity severity, DateTime since, int limit, CancellationToken ct);

    /// <summary>
    /// Marks an alert as resolved.
    /// Sets resolved_at to current UTC time and resolved_by to the specified value.
    /// </summary>
    Task ResolveAsync(string alertId, string resolvedBy, CancellationToken ct);

    /// <summary>
    /// Gets count of unresolved alerts grouped by severity.
    /// Used for dashboard summary widgets.
    /// </summary>
    Task<Dictionary<AlertSeverity, int>> GetUnresolvedCountsAsync(CancellationToken ct);
}

/// <summary>
/// SQLite implementation of IAlertRepository using Dapper.
/// All queries use explicit SQL (no ORM).
/// All IO operations have try/catch with logging.
/// </summary>
public sealed class AlertRepository : IAlertRepository
{
    private readonly IDbConnectionFactory _db;
    private readonly ILogger<AlertRepository> _logger;

    public AlertRepository(IDbConnectionFactory db, ILogger<AlertRepository> logger)
    {
        _db = db;
        _logger = logger;
    }

    /// <summary>
    /// Inserts a new alert into alert_history table.
    /// Alerts are immutable once created (except for resolved_at/resolved_by).
    /// </summary>
    public async Task InsertAsync(AlertRecord alert, CancellationToken ct)
    {
        // Validate input (negative-first)
        if (alert == null)
        {
            throw new ArgumentNullException(nameof(alert));
        }
        if (string.IsNullOrWhiteSpace(alert.AlertId))
        {
            throw new ArgumentException("AlertId cannot be null or empty", nameof(alert));
        }
        if (string.IsNullOrWhiteSpace(alert.Message))
        {
            throw new ArgumentException("Message cannot be null or empty", nameof(alert));
        }

        const string sql = """
            INSERT INTO alert_history
                (alert_id, alert_type, severity, message, details_json,
                 source_service, created_at, resolved_at, resolved_by)
            VALUES
                (@AlertId, @AlertType, @Severity, @Message, @DetailsJson,
                 @SourceService, @CreatedAt, @ResolvedAt, @ResolvedBy)
            """;

        try
        {
            await using SqliteConnection conn = await _db.OpenAsync(ct);

            CommandDefinition cmd = new(sql, new
            {
                alert.AlertId,
                alert.AlertType,
                alert.Severity,
                alert.Message,
                alert.DetailsJson,
                alert.SourceService,
                alert.CreatedAt,
                alert.ResolvedAt,
                alert.ResolvedBy
            }, cancellationToken: ct);

            await conn.ExecuteAsync(cmd);

            _logger.LogDebug("Inserted alert {AlertId} type={AlertType} severity={Severity}",
                alert.AlertId, alert.AlertType, alert.Severity);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to insert alert {AlertId}", alert.AlertId);
            throw;
        }
    }

    /// <summary>
    /// Gets all unresolved alerts (alerts without resolved_at timestamp).
    /// Uses LIMIT for safety (pagination).
    /// </summary>
    public async Task<IReadOnlyList<AlertRecord>> GetUnresolvedAsync(int limit, CancellationToken ct)
    {
        // Validate input (negative-first)
        if (limit <= 0)
        {
            throw new ArgumentException("Limit must be positive", nameof(limit));
        }

        const string sql = """
            SELECT
                alert_id AS AlertId,
                alert_type AS AlertType,
                severity AS Severity,
                message AS Message,
                details_json AS DetailsJson,
                source_service AS SourceService,
                created_at AS CreatedAt,
                resolved_at AS ResolvedAt,
                resolved_by AS ResolvedBy
            FROM alert_history
            WHERE resolved_at IS NULL
            ORDER BY created_at DESC
            LIMIT @Limit
            """;

        try
        {
            await using SqliteConnection conn = await _db.OpenAsync(ct);

            CommandDefinition cmd = new(sql, new { Limit = limit },
                cancellationToken: ct);
            IEnumerable<AlertRecord> results = await conn.QueryAsync<AlertRecord>(cmd);

            return results.ToList();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to get unresolved alerts");
            throw;
        }
    }

    /// <summary>
    /// Gets alerts by severity level since a specific timestamp.
    /// Used for filtering dashboard alerts by criticality.
    /// </summary>
    public async Task<IReadOnlyList<AlertRecord>> GetBySeverityAsync(AlertSeverity severity, DateTime since, int limit, CancellationToken ct)
    {
        // Validate input (negative-first)
        if (limit <= 0)
        {
            throw new ArgumentException("Limit must be positive", nameof(limit));
        }

        const string sql = """
            SELECT
                alert_id AS AlertId,
                alert_type AS AlertType,
                severity AS Severity,
                message AS Message,
                details_json AS DetailsJson,
                source_service AS SourceService,
                created_at AS CreatedAt,
                resolved_at AS ResolvedAt,
                resolved_by AS ResolvedBy
            FROM alert_history
            WHERE severity = @Severity
              AND created_at >= @Since
            ORDER BY created_at DESC
            LIMIT @Limit
            """;

        try
        {
            await using SqliteConnection conn = await _db.OpenAsync(ct);

            CommandDefinition cmd = new(sql, new
            {
                Severity = severity.ToString().ToLowerInvariant(),
                Since = since.ToString("O"),  // ISO8601 format
                Limit = limit
            }, cancellationToken: ct);

            IEnumerable<AlertRecord> results = await conn.QueryAsync<AlertRecord>(cmd);

            return results.ToList();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to get alerts by severity {Severity}", severity);
            throw;
        }
    }

    /// <summary>
    /// Marks an alert as resolved by updating resolved_at and resolved_by fields.
    /// Idempotent - safe to call multiple times on the same alert.
    /// </summary>
    public async Task ResolveAsync(string alertId, string resolvedBy, CancellationToken ct)
    {
        // Validate input (negative-first)
        if (string.IsNullOrWhiteSpace(alertId))
        {
            throw new ArgumentException("AlertId cannot be null or empty", nameof(alertId));
        }
        if (string.IsNullOrWhiteSpace(resolvedBy))
        {
            throw new ArgumentException("ResolvedBy cannot be null or empty", nameof(resolvedBy));
        }

        const string sql = """
            UPDATE alert_history
            SET resolved_at = datetime('now'),
                resolved_by = @ResolvedBy
            WHERE alert_id = @AlertId
              AND resolved_at IS NULL
            """;

        try
        {
            await using SqliteConnection conn = await _db.OpenAsync(ct);

            CommandDefinition cmd = new(sql, new
            {
                AlertId = alertId,
                ResolvedBy = resolvedBy
            }, cancellationToken: ct);

            int rowsAffected = await conn.ExecuteAsync(cmd);

            if (rowsAffected == 0)
            {
                _logger.LogWarning("Attempted to resolve alert {AlertId}, but it was not found or already resolved",
                    alertId);
            }
            else
            {
                _logger.LogDebug("Resolved alert {AlertId} by {ResolvedBy}", alertId, resolvedBy);
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to resolve alert {AlertId}", alertId);
            throw;
        }
    }

    /// <summary>
    /// Gets count of unresolved alerts grouped by severity level.
    /// Returns a dictionary with AlertSeverity as key and count as value.
    /// Useful for dashboard summary widgets showing alert breakdown.
    /// </summary>
    public async Task<Dictionary<AlertSeverity, int>> GetUnresolvedCountsAsync(CancellationToken ct)
    {
        const string sql = """
            SELECT
                severity AS Severity,
                COUNT(*) AS Count
            FROM alert_history
            WHERE resolved_at IS NULL
            GROUP BY severity
            """;

        try
        {
            await using SqliteConnection conn = await _db.OpenAsync(ct);

            CommandDefinition cmd = new(sql, cancellationToken: ct);

            // Query returns rows with severity (string) and count (long from SQLite)
            var results = await conn.QueryAsync<(string Severity, long Count)>(sql);

            // Convert severity strings to enum and build dictionary
            Dictionary<AlertSeverity, int> counts = new();

            foreach (var row in results)
            {
                // Parse severity string to enum (case-insensitive)
                if (Enum.TryParse<AlertSeverity>(row.Severity, ignoreCase: true, out AlertSeverity severity))
                {
                    counts[severity] = (int)row.Count;
                }
                else
                {
                    _logger.LogWarning("Unknown severity value in database: {Severity}", row.Severity);
                }
            }

            // Ensure all severity levels are present (even if count is 0)
            foreach (AlertSeverity severity in Enum.GetValues<AlertSeverity>())
            {
                if (!counts.ContainsKey(severity))
                {
                    counts[severity] = 0;
                }
            }

            return counts;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to get unresolved alert counts");
            throw;
        }
    }
}
