namespace SharedKernel.Domain;

/// <summary>
/// Types of alerts that can be sent to the Cloudflare notification system.
/// Each type may have different routing, formatting, or urgency rules.
/// </summary>
public enum AlertType
{
    /// <summary>
    /// System health alerts: CPU, RAM, disk, uptime monitoring.
    /// </summary>
    SystemHealth = 0,

    /// <summary>
    /// Trade execution alerts: order filled, rejected, partial fill.
    /// </summary>
    TradeExecution = 1,

    /// <summary>
    /// Strategy signals: entry/exit signals generated by strategy logic.
    /// </summary>
    StrategySignal = 2,

    /// <summary>
    /// Risk management alerts: margin calls, position limit breaches, drawdown warnings.
    /// </summary>
    RiskManagement = 3,

    /// <summary>
    /// Connection alerts: IBKR connection lost, reconnected, authentication failures.
    /// </summary>
    ConnectionStatus = 4,

    /// <summary>
    /// Configuration alerts: strategy loaded, reloaded, validation errors.
    /// </summary>
    Configuration = 5,

    /// <summary>
    /// Generic error alerts that don't fit other categories.
    /// </summary>
    Error = 99
}
