# Sync-KBToRules.ps1
# Sincronizza knowledge base → .claude/rules/ (top errori critici)
# Esegui SOLO a fine feature, dopo tutti i task completati

$ErrorActionPreference = "Stop"

$RulesDir = ".claude\rules"
$KBErrors = "knowledge\errors-registry.md"
$KBLessons = "knowledge\lessons-learned.md"

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "🔄 Syncing Knowledge Base → Rules" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

# Crea directory rules
New-Item -ItemType Directory -Force -Path $RulesDir | Out-Null

# ====================
# 1. Critical Errors
# ====================
Write-Host "📋 Step 1: Extracting critical errors..." -ForegroundColor Yellow

$errorHeader = @"
# Error Prevention Rules
> ⚠️ AUTO-GENERATED from knowledge/errors-registry.md
> Last sync: $(Get-Date -Format "o")

**THESE RULES ARE LOADED AUTOMATICALLY IN EVERY SESSION**

DO NOT edit this file directly. Edit knowledge/errors-registry.md and run:
``````powershell
.\scripts\Sync-KBToRules.ps1
``````

---

## Critical Errors to NEVER Repeat

"@

$errorHeader | Set-Content "$RulesDir\error-prevention.md"

# Estrai errori CRITICAL
if (Test-Path $KBErrors) {
    $content = Get-Content $KBErrors -Raw

    # Regex per estrarre blocchi ## ERR-XXX che contengono "CRITICAL"
    $errorBlocks = [regex]::Matches($content, '(?s)(## ERR-[^#]+?)(?=## ERR-|\z)')

    $criticalCount = 0
    foreach ($block in $errorBlocks) {
        if ($block.Value -match 'CRITICAL|Severity: CRITICAL') {
            $block.Value | Add-Content "$RulesDir\error-prevention.md"
            $criticalCount++
        }
    }

    Write-Host "   ✅ Extracted $criticalCount critical errors" -ForegroundColor Green
} else {
    Write-Host "   ⚠️  $KBErrors not found" -ForegroundColor Yellow
}

# ====================
# 2. Architectural Decisions
# ====================
Write-Host ""
Write-Host "🏗️  Step 2: Extracting architectural lessons..." -ForegroundColor Yellow

$archHeader = @"
# Architectural Decisions
> ⚠️ AUTO-GENERATED from knowledge/lessons-learned.md
> Last sync: $(Get-Date -Format "o")

**THESE RULES ARE LOADED AUTOMATICALLY IN EVERY SESSION**

---

## Key Architectural Lessons

"@

$archHeader | Set-Content "$RulesDir\architectural-decisions.md"

if (Test-Path $KBLessons) {
    $archLessons = Get-Content $KBLessons |
        Where-Object { $_ -match 'LESSON-\d+.*(ARCHITECTURE|DESIGN)' } |
        Select-Object -First 20 |
        ForEach-Object { $_ -replace '^- LESSON-\d+: ', '### ' }

    $archLessons | Add-Content "$RulesDir\architectural-decisions.md"

    $archCount = ($archLessons | Measure-Object).Count
    Write-Host "   ✅ Extracted $archCount architectural lessons" -ForegroundColor Green
} else {
    Write-Host "   ⚠️  $KBLessons not found" -ForegroundColor Yellow
    $archCount = 0
}

# ====================
# 3. Performance Rules
# ====================
Write-Host ""
Write-Host "⚡ Step 3: Extracting performance lessons..." -ForegroundColor Yellow

$perfHeader = @"
# Performance Rules
> ⚠️ AUTO-GENERATED from knowledge/lessons-learned.md
> Last sync: $(Get-Date -Format "o")

**THESE RULES ARE LOADED AUTOMATICALLY IN EVERY SESSION**

---

## Performance Lessons

"@

$perfHeader | Set-Content "$RulesDir\performance-rules.md"

if (Test-Path $KBLessons) {
    $perfLessons = Get-Content $KBLessons |
        Where-Object { $_ -match 'LESSON-\d+.*\[Performance\]' } |
        Select-Object -First 20 |
        ForEach-Object { $_ -replace '^- LESSON-\d+: ', '### ' }

    $perfLessons | Add-Content "$RulesDir\performance-rules.md"

    $perfCount = ($perfLessons | Measure-Object).Count
    Write-Host "   ✅ Extracted $perfCount performance lessons" -ForegroundColor Green
} else {
    Write-Host "   ⚠️  $KBLessons not found" -ForegroundColor Yellow
    $perfCount = 0
}

# ====================
# 4. Summary
# ====================
Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "✅ Sync Complete" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Updated files:"
Write-Host "  - $RulesDir\error-prevention.md ($criticalCount rules)" -ForegroundColor Cyan
Write-Host "  - $RulesDir\architectural-decisions.md ($archCount rules)" -ForegroundColor Cyan
Write-Host "  - $RulesDir\performance-rules.md ($perfCount rules)" -ForegroundColor Cyan
Write-Host ""
Write-Host "These rules will be auto-loaded in every Claude session." -ForegroundColor Yellow
Write-Host ""
