#!/usr/bin/env bash
# sync-kb-to-rules.sh
# Sincronizza knowledge base → .claude/rules/ (top errori critici)
# Esegui SOLO a fine feature, dopo tutti i task completati

set -euo pipefail

RULES_DIR=".claude/rules"
KB_ERRORS="knowledge/errors-registry.md"
KB_LESSONS="knowledge/lessons-learned.md"

echo "=========================================="
echo "🔄 Syncing Knowledge Base → Rules"
echo "=========================================="
echo ""

# Crea directory rules se non esiste
mkdir -p "$RULES_DIR"

# ====================
# 1. Critical Errors
# ====================
echo "📋 Step 1: Extracting critical errors..."

cat > "$RULES_DIR/error-prevention.md" << 'EOF'
# Error Prevention Rules
> ⚠️ AUTO-GENERATED from knowledge/errors-registry.md
> Last sync:
EOF

echo "$(date -Iseconds)" >> "$RULES_DIR/error-prevention.md"

cat >> "$RULES_DIR/error-prevention.md" << 'EOF'

**THESE RULES ARE LOADED AUTOMATICALLY IN EVERY SESSION**

DO NOT edit this file directly. Edit knowledge/errors-registry.md and run:
```bash
./scripts/sync-kb-to-rules.sh
```

---

## Critical Errors to NEVER Repeat

EOF

# Estrai errori con "Severity: CRITICAL" o "CRITICAL" nel titolo
if [ -f "$KB_ERRORS" ]; then
  # Metodo: estrai blocchi ## ERR-XXX fino al prossimo ##, se contengono CRITICAL
  awk '
    /^## ERR-/ {
      if (is_critical && buffer != "") {
        print buffer
      }
      buffer = $0 "\n"
      is_critical = 0
      in_error = 1
      next
    }
    in_error && /CRITICAL/ {
      is_critical = 1
    }
    in_error && /^---$/ {
      if (is_critical && buffer != "") {
        print buffer
      }
      buffer = ""
      is_critical = 0
      in_error = 0
      next
    }
    in_error {
      buffer = buffer $0 "\n"
    }
    END {
      if (is_critical && buffer != "") {
        print buffer
      }
    }
  ' "$KB_ERRORS" >> "$RULES_DIR/error-prevention.md"

  CRITICAL_COUNT=$(grep -c "^## ERR-" "$RULES_DIR/error-prevention.md" 2>/dev/null || true)
  CRITICAL_COUNT=${CRITICAL_COUNT:-0}
  echo "   ✅ Extracted $CRITICAL_COUNT critical errors"
else
  echo "   ⚠️  $KB_ERRORS not found"
fi

# ====================
# 2. Architectural Decisions
# ====================
echo ""
echo "🏗️  Step 2: Extracting architectural lessons..."

cat > "$RULES_DIR/architectural-decisions.md" << 'EOF'
# Architectural Decisions
> ⚠️ AUTO-GENERATED from knowledge/lessons-learned.md
> Last sync:
EOF

echo "$(date -Iseconds)" >> "$RULES_DIR/architectural-decisions.md"

cat >> "$RULES_DIR/architectural-decisions.md" << 'EOF'

**THESE RULES ARE LOADED AUTOMATICALLY IN EVERY SESSION**

---

## Key Architectural Lessons

EOF

ARCH_COUNT=0
if [ -f "$KB_LESSONS" ]; then
  # Extract lessons tagged [ARCHITECTURE] or [DESIGN]. Disable pipefail locally
  # because head closing stdin makes grep SIGPIPE under `set -o pipefail`
  # (Windows bash in particular).
  set +o pipefail
  grep -E "LESSON-[0-9]+.*\[(ARCHITECTURE|DESIGN)\]" "$KB_LESSONS" 2>/dev/null \
    | head -20 \
    | sed 's/^- LESSON-[0-9]*: /### /' \
    >> "$RULES_DIR/architectural-decisions.md" || true
  set -o pipefail

  ARCH_COUNT=$(grep -c "^###" "$RULES_DIR/architectural-decisions.md" 2>/dev/null || true)
  ARCH_COUNT=${ARCH_COUNT:-0}
  echo "   ✅ Extracted $ARCH_COUNT architectural lessons"
else
  echo "   ⚠️  $KB_LESSONS not found"
fi

# ====================
# 3. Performance Rules
# ====================
echo ""
echo "⚡ Step 3: Extracting performance lessons..."

cat > "$RULES_DIR/performance-rules.md" << 'EOF'
# Performance Rules
> ⚠️ AUTO-GENERATED from knowledge/lessons-learned.md
> Last sync:
EOF

echo "$(date -Iseconds)" >> "$RULES_DIR/performance-rules.md"

cat >> "$RULES_DIR/performance-rules.md" << 'EOF'

**THESE RULES ARE LOADED AUTOMATICALLY IN EVERY SESSION**

---

## Performance Lessons

EOF

PERF_COUNT=0
if [ -f "$KB_LESSONS" ]; then
  set +o pipefail
  grep -E "LESSON-[0-9]+.*\[Performance\]" "$KB_LESSONS" 2>/dev/null \
    | head -20 \
    | sed 's/^- LESSON-[0-9]*: /### /' \
    >> "$RULES_DIR/performance-rules.md" || true
  set -o pipefail

  PERF_COUNT=$(grep -c "^###" "$RULES_DIR/performance-rules.md" 2>/dev/null || true)
  PERF_COUNT=${PERF_COUNT:-0}
  echo "   ✅ Extracted $PERF_COUNT performance lessons"
else
  echo "   ⚠️  $KB_LESSONS not found"
fi

# ====================
# 4. Summary
# ====================
echo ""
echo "=========================================="
echo "✅ Sync Complete"
echo "=========================================="
echo ""
echo "Updated files:"
echo "  - $RULES_DIR/error-prevention.md ($CRITICAL_COUNT rules)"
echo "  - $RULES_DIR/architectural-decisions.md ($ARCH_COUNT rules)"
echo "  - $RULES_DIR/performance-rules.md ($PERF_COUNT rules)"
echo ""
echo "These rules will be auto-loaded in every Claude session."
echo ""
