namespace OptionsExecutionService.Repositories;

/// <summary>
/// Represents an outbox entry for atomic broker+DB operations.
/// Implements outbox pattern: Write intention → Execute → Mark complete.
/// Enables crash recovery by persisting order operations before execution.
/// Phase 1: State Persistence & Idempotency
/// </summary>
public sealed record OrderOutboxEntry
{
    /// <summary>
    /// Auto-generated unique identifier for this outbox entry.
    /// </summary>
    public long OutboxId { get; init; }

    /// <summary>
    /// Internal order ID (links to order_tracking table).
    /// </summary>
    public required string OrderId { get; init; }

    /// <summary>
    /// Operation type: "PlaceOrder", "CancelOrder", "ModifyOrder".
    /// </summary>
    public required string Operation { get; init; }

    /// <summary>
    /// JSON payload containing operation parameters.
    /// For PlaceOrder: OrderRequest serialized to JSON.
    /// For CancelOrder: Just the order ID.
    /// For ModifyOrder: Modified fields.
    /// </summary>
    public required string Payload { get; init; }

    /// <summary>
    /// Entry status: "pending", "sent", "failed".
    /// Pending: Not yet executed.
    /// Sent: Successfully executed and marked complete.
    /// Failed: Execution failed, needs manual review.
    /// </summary>
    public required string Status { get; init; }

    /// <summary>
    /// Timestamp when entry was created (ISO 8601 UTC).
    /// Auto-generated by database DEFAULT.
    /// </summary>
    public string? CreatedAt { get; init; }

    /// <summary>
    /// Timestamp when entry was marked as sent (ISO 8601 UTC).
    /// Null until MarkSentAsync() is called.
    /// </summary>
    public string? SentAt { get; init; }
}
